export const MOVIE_LOADED = 'MOVIE_LOADED';
export const MOVIE_UPDATED = 'MOVIE_UPDATED';
export const MOVIE_RESET = 'MOVIE_RESET';
export const MOVIES_LOADED = 'MOVIES_LOADED';
export const MOVIES_RESET = 'MOVIES_RESET';
export const ALL_MOVIES_RESET = 'ALL_MOVIES_RESET';
export const CURRENT_MOVIES_UPDATED = 'CURRENT_MOVIES_UPDATED';
